network:
  ssl:
    pem_certificate: ${HOME}/.vnc/self.pem
    pem_key: ${HOME}/.vnc/self.pem
    require_ssl: false
desktop:
  resolution:
    width: 1024
    height: 768
  allow_resize: false
  pixel_depth: 24
runtime_configuration:
  allow_override_list:
    - pointer.enabled
