
# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for Helm
  - package-ecosystem: "helm"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/src/chart"
    # Check for updates once a week
    schedule:
      interval: "daily"

  # Enable version updates for GHA
  - package-ecosystem: "github-actions"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
