environment: sorin-doru
persistence:
  size: 10Gi
ingress:
  host: openghiara-doru.huna2.com
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
mcpClientSecret: "${CLIENT_SECRET}"
vncPassword: "${VNC_PASSWORD}"