environment: oci
persistence:
  size: 10Gi
ingress:
  host: openghiara.alinflorin.isroot.in
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: default-basic-auth@kubernetescrd
mcpClientSecret: "${CLIENT_SECRET}"