nameOverride: ""
fullnameOverride: ""

environment: dev
resources: {}
persistence:
  size: 1Gi
  storageClass: ""
ingress:
  host: openghiara.example.com
  className: ""
  annotations: {}
mcpClientSecret: ""
vncPassword: ""
mcpTokenExpiry: 2592000
userScript: |
  echo Hi