environment: oci
persistence:
  size: 10Gi
ingress:
  enabled: true
  host: openghiara.alinflorin.isroot.in
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls:
    - secretName: openghiara-tls
      hosts:
        - openghiara.alinflorin.isroot.in
vncPw: ${VNC_PW}