apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openghiara
spec:
  selector:
    matchLabels:
      app: openghiara
  serviceName: openghiara
  template:
    metadata:
      labels:
        app: openghiara
    spec:
      containers:
        - name: openghiara
          image: kasmweb/core-ubuntu-noble:1.18.0-rolling-weekly
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VNCOPTIONS
              value: "-disableBasicAuth"
          ports:
            - containerPort: 6901
          volumeMounts:
            - name: data
              mountPath: /data
            - name: shm
              mountPath: /dev/shm
            - name: configs
              mountPath: /dockerstartup/vnc_startup.sh
              subPath: vnc_startup.sh
            - name: configs
              mountPath: /dockerstartup/custom_startup.sh
              subPath: custom_startup.sh
            - name: configs
              mountPath: /etc/kasmvnc/kasmvnc.yaml
              subPath: kasmvnc.yaml

      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
        - name: configs
          configMap:
            name: openghiara
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
