name: Release - Build Push Deploy

on:
  release:
    types: [released]

jobs:
  helm:
    permissions:
      actions: read
      contents: read
      packages: write
    if: ${{ github.event.release.target_commitish == 'main' }}
    uses: ./.github/workflows/reusable-helm-ci.yaml
    with:
      push: true
      scan: false
      version: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    needs: [helm]
    strategy:
      matrix:
        environment: [oci]
    if: ${{ github.event.release.target_commitish == 'main' }}
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      env: ${{ matrix.environment }}
      version: ${{ github.ref_name }}
      uninstall: false
    secrets: inherit